### ISSUE TITLE
interoperability with ethereum by using parity-bridge

### ISSUE THREAD

**Issue by hitchho** [gochain/gip#21]
how about you wont advertise your chain with promise of becoming 10 times more decentralized than ethereum if you are looking to run it in 50 nodes that would run on centralized cloud services like AWS and azure. 
instead though you could act honest and advertise that you are scaling ethereum with chain that is run by trusted network and will have interoperability with ethereum. once again you dont even need to code interoperability yourself but it is something parity/polkadot provides to you in silver platter(made to operate with POA): 
https://github.com/paritytech/parity-bridge

**Comment by treeder** [comment]
Nice way to start off an issue @hitchhooker .
