### ISSUE TITLE
GIP Request of Gaining a 254x of TPS

### ISSUE THREAD

**Issue by BeenOnChain** [gochain/gip#26]
Would it be possible to introduce a Function for Batch Transfer via a method call to allow 254 times more TPS? 

The function would be similar

With a form of automated method calls

Similar to something like;

   Function multiPartyTransferFrom(address _from, address[] _toAddresses, uint256[] _amounts) public {
        /* Ensures _toAddresses array is less than or equal to 255 */
        require(_toAddresses.length <= 255);
        /* Ensures _toAddress and _amounts have the same number of entries. */
        require(_toAddresses.length == _amounts.length);

        for (uint8 i = 0; i < _toAddresses.length; i++) {
            transferFrom(_from, _toAddresses[i], _amounts[i]);
        }

This would allow a low cost, energy effiency way of transferring more TPS. The Method Call would automatically go into place as orders are being sent across the Blockchain network. It’s something similar to the BTC blockchain.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jmank88** [comment]
I'm struggling to see how this would be more efficient than sending individual transactions. Won't the gas used scale linearly? e.g. sending a batch of 254 txs will use 254 times as much gas (and take 254 times as long to execute). The amount of work being done is the same whether they are batched or separate.

**Comment by BeenOnChain** [comment]
@jmank88 
>I'm struggling to see how this would be more efficient than sending individual transactions. Won't the gas used scale linearly? e.g. sending a batch of 254 txs will use 254 times as much gas (and take 254 times as long to execute). The amount of work being done is the same whether they are batched or separate.

@jmank88  as orders go into the Go blockchain , they are grouped into a block together at high capacity times, actually reducing the amount of gas needed. So instead of going individual transaction block by individual transaction block. The blocks are instead composed to the max 254 transaction per block.

**Comment by jmank88** [comment]
Why would grouping reduce the amount of gas needed? The same amount of work is being done either way.

Additionally, grouping for later processing would come with a latency penalty.

**Comment by BeenOnChain** [comment]
@jmank88 So what would happen if I spammed 1300 Individual transactions of 50 Go coins per second? Would it not bog down the network?

However if they are batched together it would just group the spam. It would also leave more space in other transaction blocks to be processed.

**Comment by jmank88** [comment]
A batch of 1300 txs takes just as long to process (and uses as much gas) as 1300 individual txs. Each block is already quite literally a batch of txs.

A smart contract transaction which executes a batch of internal txs still uses an amount of gas which scales linearly with the number of txs - it does not count as a single transaction in terms of gas or execution time.

**Comment by treeder** [comment]
Your batch transaction took 3115001 gas on the etherscan link you sent me, what Jordan is saying is that it would take a similar amount to just do separate transactions. And it's actually less risky to do them separately since if your batch failed somewhere along the way, you'd lose all the gas up to that point.

**Comment by BeenOnChain** [comment]
@jmank88 so what you’re saying is;

Sending a single mass order of 1 million Gocoins would take the same amount of time as sending 
Batched Hundreds of individual Go transactions adding up to 1 million coins?

**Comment by BeenOnChain** [comment]
@jmank88 because that’s what I’m trying to say!

Instead of letting micro orders bog the network down, batch them into the same block ie single transaction

**Comment by treeder** [comment]
And wouldn't actually increase the tps unfortunately.

**Comment by jmank88** [comment]
>  @jmank88 so what you’re saying is;
> 
> Sending a single mass order of 1 million Gocoins would take the same amount of time as sending
> Batched Hundreds of individual Go transactions adding up to 1 million coins?

If they are being sent to multiple different destination addresses (as in your code example), then yes.

**Comment by BeenOnChain** [comment]
[T1=B1,B2,B3,...MAX BLOCKSIZE] > [T2=B1,B2,B3,...MAXBLOCKSIZE] >
[T3=B1,B2,B3,...MAX BLOCKSIZE] > [T4=B1,B2,B3,...MAX ] >
...
[T1299=B1,B2,B3,...MAX] > [T1300=B1,B2,B3,...MAX] 

?

**Comment by jmank88** [comment]
> [T1=B1,B2,B3,...MAX BLOCKSIZE] > [T2=B1,B2,B3,...MAXBLOCKSIZE] >
> [T3=B1,B2,B3,...MAX BLOCKSIZE] > [T4=B1,B2,B3,...MAX ] >
> ...
> [T1299=B1,B2,B3,...MAX] > [T1300=B1,B2,B3,...MAX]
> 
> ?

If this is a question, you are going to have to elaborate.

To be clear, the block limit is measured in gas, not literally in the number of txs. `1300` *standard transactions* (`21000` gas per tx) per second with 5 second blocks is `136500000` gas - our current block gas limit. Executing a single smart tx which actually performs a batch of txs internally does not count as a single tx - it uses as much gas as it uses. In the case of the Ethereum example you sent us, it used over 3 million gas - which is roughly as much gas as 143 standard transactions would use. Yes, the gas costs may be reduced by batching, but the operation is still `O(n)`. Regardless, those incentives already exist - any smart contract author is free to choose to use this technique or not, without any changes to the EVM on our part.

**Comment by BeenOnChain** [comment]
👍🏾 @jmank88

**Comment by BeenOnChain** [comment]
@jmank88 I think also it would it would be a great implementation along with your current one for further lessening of gas usage; however I know you said it should just be in the smart contracts. But would be dope for it too automatically Happen in the blockchain.
