### ISSUE TITLE
[GIP] Increase minimum gas price by 1000x

### ISSUE THREAD

**Issue by treeder** [gochain/gip#29]
## Simple Summary

Increase minimum gas price. 

## Overview

This is a proposal to increase the minimum gas price that nodes will accept by 1000x.

## Motivation 

UPDATE: GO price has gone up since this was created, so be sure to adjust for current price. 

Gas on the GoChain network is extremely low. The following are the current transactions costs, USD equivalent based on $0.01 per GO:

* A normal GO transfer transaction costs 0.000042 GO ($0.00000042)
* An GO20 transfer transaction costs ~0.0001 GO ($0.000001)
* A complex transaction (a uniswap swap transaction) costs ~0.00025 GO ($0.0000025)
* 1 GO (or 1 cent) is all it costs for 23,809 transactions

The problems with the cost being too low:

* Even at full capacity of 1300 transactions per second, the fees will not generate enough to even cover the bare minimum cost of running the network.
* It would be very cheap for someone to saturate the network and degrade service for everyone else. $0.036 per day is all it would cost to submit 1300 transactions per second.
* The extremely low cost of a transaction, means the value of GO is also very low
* Without more fees, the cost of running the network relies on block rewards which means there will always need to be inflation
* Enterprise partners understand that they should pay a reasonable amount for their infrastructure. The current price is so low that it is nearly free for enterprises. Fees can be increased 100-1,000x without exceeding the threshold of what a reasonable fee is for enterprises.

Fees collected at current price at 10 transactions per second: $25.92 per month

At 1000x the price:

* A normal GO transfer transaction would cost 0.042 GO ($0.00042)
* A GO20 transfer transaction would cost ~0.1 GO ($0.001)
* A complex transaction (a uniswap swap transaction) would cost ~0.25 GO ($0.0025)
* Fees paid at 10 tps: $25,920

Increasing the gas would increase the value of the entire network, set a fair price for using the network (it shouldn’t be free), reduce the chance of network saturation and can lead to being able to reduce block or remove block rewards (see [GIP-30](https://github.com/gochain/gips/issues/30)). 

## Specification

Nodes would reject transactions below 2000 gwei. Currently 2 gwei.

[eth_gasPrice](https://eth.wiki/json-rpc/API) would return a minimum of 2000 gwei.

**Comment by dcyounts** [comment]
Makes a lot of sense.

**Comment by danoand** [comment]
This is an excellent point.  One major driver for pricing fees "correctly" is to protect the network from "bad actors".

> * It would be very cheap for someone to saturate the network and degrade service for everyone else. $0.036 per day is all it would cost to submit 1300 transactions per second.

**Comment by spendlove24** [comment]
Agreed

**Comment by smahmoud822** [comment]
Good idea now fee is nothing let make it something

**Comment by timhnc75** [comment]
Its still so cheap it doesnt matter if we raise it we could raise it to .01 and nobody would blink an eye.

**Comment by treeder** [comment]
## Vote Details

start_time:2020-12-10T20:00:00Z
end_time:2020-12-12T20:00:00Z
contract_address:0x733D1e256af14B111611663739AAde12BcBc6A73
choice_1:yes:0xdfb1fFceebCB9b9737C29B8B338D87f196C62e86
choice_2:no:0xD10aF548625E68F97013FaE2d14343EBa46C6952

**Comment by treeder** [comment]
This is rolled out on testnet, we are currently testing developer and user tools to ensure things work properly. 

- [x] web3 cli
- [x] web3.js
- [x] metamask

**Comment by treeder** [comment]
This is going live on mainnet in one week...
